```
global:
  scrape_interval: 15s

scrape_configs:
  #- job_name: 'prometheus-self'
  #  static_configs:
  #    - targets: ['localhost:9090']

  - job_name: 'kube-state-metrics'
    metrics_path: /metrics
    scrape_interval: 15s    
    static_configs:
      - targets: ['10.128.0.2:30080']
  
  - job_name: 'kubelet'
    scheme: https
    metrics_path: /metrics
    scrape_interval: 15s
    tls_config:
      ca_file: /etc/prometheus/ca.crt
    bearer_token_file: /etc/prometheus/token
    static_configs:
      - targets: ['10.128.0.2:10250']
        labels:
          node: microk8s-01

  - job_name: 'kubelet-cadvisor'
    scheme: https
    metrics_path: /metrics/cadvisor
    scrape_interval: 15s
    tls_config:
      ca_file: /etc/prometheus/ca.crt
    bearer_token_file: /etc/prometheus/token
    static_configs:
      - targets: ['10.128.0.2:10250']
```
